In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv("/content/loan_default_classification_dataset.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1020 non-null   object
 1   Age                1020 non-null   int64
 2   Gender             990 non-null    object
 3   Annual_Income      989 non-null    object
 4   Credit_Score       989 non-null    float64
 5   Loan_Amount        1020 non-null   int64
 6   Loan_Tenure        1020 non-null   object
 7   Employment_Status  1020 non-null   object
 8   Existing_EMI       1020 non-null   int64
 9   Region             1020 non-null   object
 10  Default            1020 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 87.8+ KB

In [19]:
df

,Customer_ID,Age,Gender,Annual_Income,Credit_Score,Loan_Amount,Loan_Tenure,Employment_Status,Existing_EMI,Region,Default
0,C0001,59,Female,370326.0,750.0,541048,10,Salaried,25914,East,0
1,C0002,49,Male,1178879.0,577.0,652439,10,Business,28548,North,1
2,C0003,35,Male,939282.0,761.0,373452,19,Business,9497,North,0
3,C0004,28,Female,520971.0,722.0,340853,18,Business,12933,South,0
4,C0005,41,Male,NaN,620.0,276743,16,Self-Employed,23519,South,0
...,...,...,...,...,...,...,...,...,...,...,...
1015,C0900,45,Female,1046084.0,619.0,422959,9,Business,27340,West,1
1016,C0281,25,Male,1163663.0,633.0,169087,18,Salaried,18833,East,0
1017,C0884,39,Male,1330697.0,763.0,721825,14,Self-Employed,25002,East,0
1018,C0762,45,Female,373997.0,797.0,542899,4,Salaried,7283,East,0
1019,C0320,55,Male,1286753.0,648.0,397142,3,Self-Employed,27622,West,0

In [20]:
df.isnull().sum()

Customer_ID           0
Age                   0
Gender               30
Annual_Income        31
Credit_Score         31
Loan_Amount           0
Loan_Tenure           0
Employment_Status     0
Existing_EMI          0
Region                0
Default               0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(20)

In [22]:
df.drop_duplicates(inplace=True)

In [23]:
df.isnull().sum()

Customer_ID           0
Age                   0
Gender               30
Annual_Income        30
Credit_Score         30
Loan_Amount           0
Loan_Tenure           0
Employment_Status     0
Existing_EMI          0
Region                0
Default               0
dtype: int64

In [24]:
df.isnull().sum()

Customer_ID           0
Age                   0
Gender               30
Annual_Income        30
Credit_Score         30
Loan_Amount           0
Loan_Tenure           0
Employment_Status     0
Existing_EMI          0
Region                0
Default               0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1000 non-null   object
 1   Age                1000 non-null   int64
 2   Gender             970 non-null    object
 3   Annual_Income      970 non-null    object
 4   Credit_Score       970 non-null    float64
 5   Loan_Amount        1000 non-null   int64
 6   Loan_Tenure        1000 non-null   object
 7   Employment_Status  1000 non-null   object
 8   Existing_EMI       1000 non-null   int64
 9   Region             1000 non-null   object
 10  Default            1000 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 93.8+ KB

In [28]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [32]:
df.isnull().sum()

Customer_ID           0
Age                   0
Gender                0
Annual_Income         0
Credit_Score         30
Loan_Amount           0
Loan_Tenure           0
Employment_Status     0
Existing_EMI          0
Region                0
Default               0
dtype: int64

In [31]:
df['Annual_Income']= df['Annual_Income'].fillna(df['Annual_Income'].mode()[0])

In [33]:
df['Credit_Score'] = df['Credit_Score'].fillna(df['Credit_Score'].mean())

In [34]:
df.isnull().sum()

Customer_ID          0
Age                  0
Gender               0
Annual_Income        0
Credit_Score         0
Loan_Amount          0
Loan_Tenure          0
Employment_Status    0
Existing_EMI         0
Region               0
Default              0
dtype: int64

In [59]:
from sklearn.preprocessing import LabelEncoder

In [62]:
obj = LabelEncoder()

In [38]:
df.drop('Customer_ID',axis=1)

,Age,Gender,Annual_Income,Credit_Score,Loan_Amount,Loan_Tenure,Employment_Status,Existing_EMI,Region,Default
0,59,Female,370326.0,750.0,541048,10,Salaried,25914,East,0
1,49,Male,1178879.0,577.0,652439,10,Business,28548,North,1
2,35,Male,939282.0,761.0,373452,19,Business,9497,North,0
3,28,Female,520971.0,722.0,340853,18,Business,12933,South,0
4,41,Male,not_available,620.0,276743,16,Self-Employed,23519,South,0
...,...,...,...,...,...,...,...,...,...,...
995,58,Male,1270834.0,660.0,322128,16,Business,21924,West,0
996,22,Female,815693.0,600.0,774533,16,Salaried,26894,North,1
997,27,Male,839570.0,750.0,470250,15,Salaried,29845,East,0
998,38,Male,539017.0,709.0,386663,14,Self-Employed,29310,East,0
999,47,Male,714994.0,624.0,480714,11,Business,10131,South,1

In [63]:
for col in df.columns:
  if (df[col].dtypes == "object64"):
    df[col] = obj.fit_transform(df[col])

In [60]:
le=LabelEncoder()
for col in df.columns:
    if (df[col].dtype == 'object')  &  (col !="Churn") :
        df[col]=le.fit_transform(df[col])

In [64]:
df

,Customer_ID,Age,Gender,Annual_Income,Credit_Score,Loan_Amount,Loan_Tenure,Employment_Status,Existing_EMI,Region,Default
0,0,59,0,370326,750.0,541048,10,1,25914,0,0
1,1,49,1,1178879,577.0,652439,10,0,28548,1,1
2,2,35,1,939282,761.0,373452,19,0,9497,1,0
3,3,28,0,520971,722.0,340853,18,0,12933,2,0
4,4,41,1,1000336,620.0,276743,16,2,23519,2,0
...,...,...,...,...,...,...,...,...,...,...,...
995,995,58,1,1270834,660.0,322128,16,0,21924,3,0
996,996,22,0,815693,600.0,774533,16,1,26894,1,1
997,997,27,1,839570,750.0,470250,15,1,29845,0,0
998,998,38,1,539017,709.0,386663,14,2,29310,0,0
999,999,47,1,714994,624.0,480714,11,0,10131,2,1

In [45]:
df['Annual_Income'] = df['Annual_Income'].replace('not_available', np.nan)
df['Annual_Income'] = df['Annual_Income'].fillna(df['Annual_Income'].mode()[0])
df['Annual_Income'] = df['Annual_Income'].astype(float).astype(int)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1000 non-null   object
 1   Age                1000 non-null   int64
 2   Gender             1000 non-null   object
 3   Annual_Income      1000 non-null   int64
 4   Credit_Score       1000 non-null   float64
 5   Loan_Amount        1000 non-null   int64
 6   Loan_Tenure        1000 non-null   int64
 7   Employment_Status  1000 non-null   object
 8   Existing_EMI       1000 non-null   int64
 9   Region             1000 non-null   object
 10  Default            1000 non-null   int64
dtypes: float64(1), int64(6), object(4)
memory usage: 126.0+ KB

In [52]:
df['Loan_Tenure'] =df['Loan_Tenure'].astype(float).astype(int)

In [53]:
df['Loan_Tenure'].unique()

array([10, 19, 18, 16, 13,  9, 15, 17, 11,  5,  7, 12, 14,  4,  8,  6,  3])

In [50]:
df['Loan_Tenure'] = df['Loan_Tenure'].replace('ten',10)

In [65]:
# logistic modle

from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [70]:
modle_1 = LogisticRegression()

x = df.drop('Default',axis= 1)

In [67]:
x = df.drop('Default',axis= 1)

y = df['Default']

In [72]:
x_train ,x_test ,y_train, y_test = train_test_split(x,y,train_size=0.80,random_state=0)

In [73]:
modle_1.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [79]:
from sklearn.metrics import accuracy_score

In [83]:
y_pred_1 = modle_1.predict(x_test)

In [95]:
acc_1=accuracy_score(y_pred_1,y_test)*100

In [85]:
modle_2 = DecisionTreeClassifier()

In [86]:
modle_2.fit(x_train,y_train)

DecisionTreeClassifier()

In [87]:
y_pred_2 =modle_2.predict(x_test)

In [93]:
acc_2=accuracy_score(y_pred_2,y_test)*100

In [94]:
modle_3 = RandomForestClassifier()
modle_3.fit(x_train,y_train)
y_pred_3 = modle_3.predict(x_test)
acc_3=accuracy_score(y_pred_3,y_test)*100

In [96]:
print('The accuracy score of Logistic refression is :',acc_1)
print('The accuracy score of Decision Tree classifier is :',acc_2)
print('The accuracy score od Random forest tree is :', acc_3)

The accuracy score of Logistic refression is : 85.5
The accuracy score of Decision Tree classifier is : 99.5
The accuracy score od Random forest tree is : 100.0